### ISSUE TITLE
homebrew formula should not include postgresql as a dependency

### ISSUE THREAD

**Issue by qwesda** [amjith/pgcli#135]
Hi,

the homebrew formula contains postgresql as a dependency. I don't think this is optimal since people who want to use pgcli will propably already have a postgres instance up and running, but it must not necessarily be the homebrew variant. Fixing this issue will be trivial but it should be coordinated with the person who contributed the formula.

**Comment by amjith** [comment]
I'm actually on the fence on this one. 

I asked the same question in the original issue #73 for the homebrew formula. But without that dependency the formula won't succeed in a sandboxed environment. If it doesn't succeed in the sandboxed env, then the formula is not accepted. 

So that dependency became mandatory. There is an alternative to that which is brew installing from source `brew install --build-from-source`, which will skip installing postgres if it is available in the $PATH.

I'll highlight that in the README.

**Comment by amjith** [comment]
I've updated the README (897934711872ecfa5cd66e967f1dc1d045464adc) and the website (https://github.com/amjith/pgcli.com/commit/37d37d4e150af8174e147ac5afb92c51bc943fe6).

**Comment by qwesda** [comment]
I see the problem ... sorry I only looked through the open issues. 
This issue can be closed and marked as a dupe. Maybe it could be discussed later (when the source code is more stable) if building from source, and not having the dependency, is preferable.
