### ISSUE TITLE
requset support: COPY command auto-completion

### ISSUE THREAD

**Issue by Septembers** [amjith/pgcli#146]
see http://www.postgresql.org/docs/9.3/static/sql-copy.html

**Comment by amjith** [comment]
Can you explain a little bit more? 

Would you like to see auto-completion support for the COPY command or is COPY command failing to run?

**Comment by Septembers** [comment]
auto-completion support <code>COPY</code> command

**Comment by amjith** [comment]
I've added preliminary support for the COPY command in master. I say preliminary because when you type `COPY <tab>` it'll list all the schemas and tables, which is expected. But when you type `COPY table_name FROM <tab>`, it still displays the tables, which is not the expected behavior since it should be completing filenames. But that'll take some more work so I'm going to punt on that for a bit. :)

Would you mind trying it out? You can install directly from the git repo using the following command: 

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

**Comment by Septembers** [comment]
thanks.
