### ISSUE TITLE
Automatically quote some arguments

### ISSUE THREAD

**Issue by svenstaro** [amjith/pgcli#31]
For instance, my postgresql database has a column called "order" but obviously typing that in will result in a syntax error as it expects this to be the ORDER BY clause. You should detect some of these keywords which are actually columns and quote them with double quotes.

**Comment by amjith** [comment]
I'm hesitant to have `pgcli` do "magicky" things to a query, since that's a slippery slope. 

There is no reliable way to detect if something is a column name or a keyword. So doing this would require a full sql parser and even then it could lead to some undesirable behavior in odd edge cases.

So I'm leaning towards to "Won't Fix" for this one, unless you manage to convince me otherwise. :)

**Comment by svenstaro** [comment]
Well its autocompletion already is kinda magicky. But I agree, now that I think about it, it's not easily do-able.
