### ISSUE TITLE
Add support for several "\dX" commands

### ISSUE THREAD

**Issue by marcelofernandez** [amjith/pgcli#72]
Standard pgsql supports a lot of \dX commands, for example \dn (to show schemas), \ds to show sequences, etc., but pgcli only seems to know about \d, \dv, \dt and \dt. 

Any other \dX gives a syntax error:

    postgres> \dn
    ERROR:  syntax error at or near "\"
    LINE 1: \dn
            ^

**Comment by amjith** [comment]
The rest of the commands are slowly being added (in fact, there is a pending PR for `\dn`). 

Unfortunately this will be a slow progress to add them in one at a time since I can't just pass on the special commands directly to Postgres. Each command requires reimplementing the functionality from psql into pgcli. 

So I'll start adding new ones.

**Comment by amjith** [comment]
Added `\dn` in version 0.11.0

https://pypi.python.org/pypi?:action=display&name=pgcli&version=0.11.0

**Comment by amjith** [comment]
All the special commands requested here are now added. 

\dv, \dn, \ds. 

You can install directly from the git repo to test it out: 

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```
